name = "EllipsisNotation"
uuid = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
version = "1.8.1"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
StaticArrayInterface = "0d7ed370-da01-4f52-bd93-41d350b8b718"

[compat]
AllocCheck = "0.2"
Aqua = "0.8"
ExplicitImports = "1.6"
JET = "0.9, 0.10, 0.11"
PrecompileTools = "1"
SafeTestsets = "0.1"
StaticArrayInterface = "1.2"
Test = "1"
julia = "1.10"

[extras]
AllocCheck = "9b6a8646-10ed-4001-bbdc-1d2f46dfbb1a"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AllocCheck", "ExplicitImports", "Aqua", "JET", "Test", "SafeTestsets"]
