name = "EllipsisNotation"
uuid = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "1.8.0"

[deps]
StaticArrayInterface = "0d7ed370-da01-4f52-bd93-41d350b8b718"

[compat]
Aqua = "0.8"
SafeTestsets = "0.1"
StaticArrayInterface = "1.2"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test", "SafeTestsets"]
